### ISSUE TITLE
3d print guide

### ISSUE THREAD

**Issue by ThEWiZ76** [gobbyo/clock#1]
Hi!

First off, great work mate! Thank you for this. 
I have read all documentation and files, but couldn't find any clues on the 3d printing stuff. Some parts exist 3 times with slight differences, but it is not clear what to choose. If you could extend the documentation with the differences and how many copies of each part you need, it would be a great help to a lot of people.

Thank you again for your time and effort and sharing it with the community! 👍

**Comment by JackOrms** [comment]
Could you maybe include a parts list in general? Including the LED's for inside the segments, circuit components etc etc?

Looking forwards to putting this together!

**Comment by ThEWiZ76** [comment]
I decided to do trail and error in the meantime, when complete and functioning I will post it here.

**Comment by JackOrms** [comment]
@ThEWiZ76

I am also going to do this & then we can compare notes if needs be.

**Comment by ThEWiZ76** [comment]
@JackOrms 
I decided to make some changes to the electronics. I use off the shelf boards for the motor controls and leds (pwm) and an esp32 connected to Home Assistant. The boards will be controlled over I2C. I got these parts for **electronics**:

https://www.amazon.nl/dp/B0C6M9LLXR (servo's, 2x 20 pcs)
https://www.amazon.nl/dp/B07CRDCP8V (servo controllers, 2 pcs)
https://www.amazon.nl/dp/B0B5RD9MBR (led controllers, 2 pcs)
https://www.amazon.nl/dp/B0CBX1WYXV (leds 3mm blue)

Still need to find a decent 5V power supply with enough watts, but I may sacrifice an old charger.

I decided to use the sensor data out of Home Assistant as source for the temperature etc, so no need for sensors.

**I printed these parts:**

1x frame-part-1, 2 , 3 and 4

1x clockface1
1x clockface2

1x clock-back1 (modded the Blender file to my needs)
3x clock-back2 (also modded the Blender file)
1x clock-back3 (also modded)

2x segment-3-part-a
2x segment-3-part-b
12x segment-2-part
16x segment-1-part

30x servoholder-part
30x servoholder-cap-part

30x gear

16x led1
40x led2

Printing **done** (finally) so next stop is assembling the servo parts (and test before I connect them to the back plates with this tool: https://www.amazon.nl/dp/B086TSLVV5). And after that getting everything working and tuned!

**Comment by JackOrms** [comment]
@ThEWiZ76
Interesting, using off the shelf boards was a good move! I also like the HA integration, it's something I've started playing around with more recently.

You've got further than me, I haven't even started the printing yet... carpet fitted next week and then it can come back out to play/work.

I have however had some PCB's made by a friend using the Gerber files included in the original project & got all of the components fitted to them. Sourcing them was a nightmare but I think I've got it all now. Will confirm once I know it works (or doesn't!).

The file set you have looks good, very similar to what I had selected so that's a sigh of relief.

Regarding the 5V supply, I was planning on using a MeanWell LPV-35-5 that I have on the shelf from a previous project, I think it cost around £12 and is capable of 5A. They also have others ranging from 3A to 12A so should be plenty...

**Comment by gobbyo** [comment]
> Hi!
> 
> First off, great work mate! Thank you for this. I have read all documentation and files, but couldn't find any clues on the 3d printing stuff. Some parts exist 3 times with slight differences, but it is not clear what to choose. If you could extend the documentation with the differences and how many copies of each part you need, it would be a great help to a lot of people.
> 
> Thank you again for your time and effort and sharing it with the community! 👍

I've been redesigning this entire project as the servo approach doesn't last more than 6 to 12 months.  I'll provide all the 3d print details along with links on the new design shortly.

**Comment by gobbyo** [comment]
> @ThEWiZ76 Interesting, using off the shelf boards was a good move! I also like the HA integration, it's something I've started playing around with more recently.
> 
> You've got further than me, I haven't even started the printing yet... carpet fitted next week and then it can come back out to play/work.
> 
> I have however had some PCB's made by a friend using the Gerber files included in the original project & got all of the components fitted to them. Sourcing them was a nightmare but I think I've got it all now. Will confirm once I know it works (or doesn't!).
> 
> The file set you have looks good, very similar to what I had selected so that's a sigh of relief.
> 
> Regarding the 5V supply, I was planning on using a MeanWell LPV-35-5 that I have on the shelf from a previous project, I think it cost around £12 and is capable of 5A. They also have others ranging from 3A to 12A so should be plenty...

When the display is transitioning with the most segments to the "on" position, I recall that it'll burn around 3A.  I've been using a 5v 4A power supply with no issues.

**Comment by ThEWiZ76** [comment]
> > Hi!
> > First off, great work mate! Thank you for this. I have read all documentation and files, but couldn't find any clues on the 3d printing stuff. Some parts exist 3 times with slight differences, but it is not clear what to choose. If you could extend the documentation with the differences and how many copies of each part you need, it would be a great help to a lot of people.
> > Thank you again for your time and effort and sharing it with the community! 👍
> 
> I've been redesigning this entire project as the servo approach doesn't last more than 6 to 12 months. I'll provide all the 3d print details along with links on the new design shortly.

Hey, any ETA on that? I have seen on instructables posts about a new design from 5 months ago. It will help me decide to finish this one or wait for the next.
