### ISSUE TITLE
PCB Schematic

### ISSUE THREAD

**Issue by hirushiharan** [gobbyo/clock#2]
Hi @gobbyo,

Thank you for this repository, excellent work. Additionally, could you please include the schematic of this circuit? Also, if you could elaborate a bit more on the details, it would be helpful.

Thanks & regards,
Hiru

**Comment by ThEWiZ76** [comment]
Isn't this what you are looking for? https://github.com/gobbyo/clock/wiki/circuitassembly

**Comment by hirushiharan** [comment]
Hi @ThEWiZ76,

Yes, I asked for this. Thanks
